"""initial schema

Revision ID: 10c0a6918c73
Revises: 
Create Date: 2026-09-12 11:37:49.231628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c0a6918c73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'FINISHED', name='tournamentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('belt_rank', sa.String(length=60), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Enum('SPARRING', name='discipline'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('age_label', sa.String(length=60), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('belt_group', sa.Enum('COLOR', 'BLACK', name='beltgroup'), nullable=False),
    sa.Column('weight_label', sa.String(length=60), nullable=False),
    sa.Column('rounds_to_win', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'category_id', name='uq_athlete_category')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('athlete_red_id', sa.Integer(), nullable=True),
    sa.Column('athlete_blue_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('next_match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BYE', 'FINISHED', name='matchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_blue_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['athlete_red_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], ),
    sa.ForeignKeyConstraint(['next_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket_id', 'round_number', 'slot', name='uq_match_slot')
    )
    op.create_table('round_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('red_points', sa.Integer(), nullable=False),
    sa.Column('blue_points', sa.Integer(), nullable=False),
    sa.Column('round_winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['round_winner_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'round_number', name='uq_round_per_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_scores')
    op.drop_table('matches')
    op.drop_table('registrations')
    op.drop_table('brackets')
    op.drop_table('categories')
    op.drop_table('athletes')
    op.drop_table('tournaments')
    op.drop_table('clubs')
    # ### end Alembic commands ###
