"""add min_weight and max_weight to categories

Revision ID: d63c6c668bd4
Revises: 10c0a6918c73
Create Date: 2026-09-14 10:42:01.888886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63c6c668bd4'
down_revision: Union[str, Sequence[str], None] = '10c0a6918c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('min_weight', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('max_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'max_weight')
    op.drop_column('categories', 'min_weight')
    # ### end Alembic commands ###
